POST http://localhost:3001/signup
Content-Type: application/json

{
  "userId": "65defc510860db8a46a6d4b9",
  "age": 20,
  "city": "rustavi",
  "phone": 551515646
}


###

PUT http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJCZWthIiwibGFzdE5hbWUiOiJMb21zYWR6ZSIsImVtYWlsIjoiYmVrYS5sb21zYWR6ZS4xQGJ0dS5lZHUuZ2UiLCJpYXQiOjE3MTA5MjMwOTIsImV4cCI6MTcxMDkzNzQ5Mn0.RRuYS4PpKkO0y4rV8BvL2-TyxtmT0GJwrebzhWE7Tw4
Content-Type: application/json

{
  "firstName": "Updated First Name",
  "completed": 2
}
###

POST http://localhost:3001/api/lessons
Content-Type: application/json

{
  "title": "intro to javascript",
  "userId":"65a907127f15d279458566de"
}